### ISSUE TITLE
bug in uye game

### ISSUE THREAD

**Issue by Ma1icious** [BBWATB/mini-games#3]
hey bro, i found a bug in the game called "uye.exe".
when the ball touches a brick, it has a chance to move forward without bouncing, and it will shake.
do you have time to fix it?

**Comment by Ma1icious** [comment]
Or is this actually a game mechanism?

**Comment by Ma1icious** [comment]
@ABA2396

**Comment by ABA2396** [comment]
There is a real problem with entering two decision ranges at the same time, and I'm trying to solve it

**Comment by Ma1icious** [comment]
> There is a real problem with entering two decision ranges at the same time, and I'm trying to solve it

Hey, bro. I know the cause of the bug!
If the ball collids with both blocks (for example, its coordinates coincide with the bottom of both blocks after a refresh), its speed will be multiplied twice by -1!
A very simple solution is to increment the return value in function `Check_crash`, increment the judgment on the return value at the call (line 167 in source.cpp), and break the loop immediately when its motion state changes.
Of course, there may be simpler ways to wait for your discovery.

**Comment by ABA2396** [comment]
Now it's still a problem to hit two blocks from the side at the same time, I'll see when I have time

**Comment by Ma1icious** [comment]
> Now it's still a problem to hit two blocks from the side at the same time, I'll see when I have time

okay, i'll close this issue
